In [95]:
import pandas as pd
data = {
     "name":["ilma","aliya","anas","misbah"],
     "marks":[100,99,94,43],
     "ispass":[True,True,False,True]
}
print(data)
table = pd.DataFrame(data)
print(table)
print(table.index)
print(table.columns)

{'name': ['ilma', 'aliya', 'anas', 'misbah'], 'marks': [100, 99, 94, 43], 'ispass': [True, True, False, True]}
     name  marks  ispass
0    ilma    100    True
1   aliya     99    True
2    anas     94   False
3  misbah     43    True
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'marks', 'ispass'], dtype='str')

In [52]:

arr1=["ilma","aliya","anas","misbah"]
S1=pd.Series(arr1,["one","two","three","four"])
print(S1)
print(S1["one"])
print(S1.iloc[2])

one        ilma
two       aliya
three      anas
four     misbah
dtype: str
ilma
anas

In [66]:
arr=[1,2,3,4,5,6,7,8,9,10]
s=pd.Series(arr,["a","b","c","d","e","f","g","h","i","j"])
print(s.iloc[2])
print(s.loc["e"])

3
5

In [73]:
arr3=pd.Series([1,2,3,4])
arr4=pd.Series([5,6,7,8])
sum=arr3+arr4
print(sum)

0     6
1     8
2    10
3    12
dtype: int64

In [92]:
print(arr3)
op=arr3.drop(0)
print(arr3)
print(op)

0    1
1    2
2    3
3    4
dtype: int64
0    1
1    2
2    3
3    4
dtype: int64
1    2
2    3
3    4
dtype: int64

In [101]:
df=pd.DataFrame(
    [["ilma",18],
    ["aliya",19],
    ["anas",15]],columns=["name","age"]
)
print(df)

    name  age
0   ilma   18
1  aliya   19
2   anas   15

In [113]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr_2D,columns=["A","B","CC"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [400]:
csvData=pd.read_csv("file.csv")
print(csvData)
print(csvData.head())
print(csvData.tail())
print(csvData.sample())
print(csvData.info())
print(csvData.shape)
print(csvData.columns)
print(csvData.nunique())
print(csvData.describe())
print(csvData.loc[0,3])

    Name  Age     City Course  Marks  Attendance
0   Ilma   22  Aligarh    MCA     88          92
1  Aliya   21    Delhi    BCA     91          89
2   Anas   19     Agra    BSc     76          81
3   Sara   23  Lucknow    MCA     85          95
4   Aman   20    Noida  BTech     79          84
5   Zoya   22  Aligarh    BCA     93          97
    Name  Age     City Course  Marks  Attendance
0   Ilma   22  Aligarh    MCA     88          92
1  Aliya   21    Delhi    BCA     91          89
2   Anas   19     Agra    BSc     76          81
3   Sara   23  Lucknow    MCA     85          95
4   Aman   20    Noida  BTech     79          84
    Name  Age     City Course  Marks  Attendance
1  Aliya   21    Delhi    BCA     91          89
2   Anas   19     Agra    BSc     76          81
3   Sara   23  Lucknow    MCA     85          95
4   Aman   20    Noida  BTech     79          84
5   Zoya   22  Aligarh    BCA     93          97
   Name  Age   City Course  Marks  Attendance
4  Aman   20  Noida  BTech     79          84
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         6 non-null      int64
 2   City        6 non-null      str
 3   Course      6 non-null      str
 4   Marks       6 non-null      int64
 5   Attendance  6 non-null      int64
dtypes: int64(3), str(3)
memory usage: 500.0 bytes
None
(6, 6)
Index(['Name', 'Age', 'City', 'Course', 'Marks', 'Attendance'], dtype='str')
Name          6
Age           5
City          5
Course        4
Marks         6
Attendance    6
dtype: int64
             Age      Marks  Attendance
count   6.000000   6.000000    6.000000
mean   21.166667  85.333333   89.666667
std     1.471960   6.713171    6.250333
min    19.000000  76.000000   81.000000
25%    20.250000  80.500000   85.250000
50%    21.500000  86.500000   90.500000
75%    22.000000  90.250000   94.250000
max    23.000000  93.000000   97.000000

In [198]:
print(csvData.Name)
print(csvData["Name"][0])
print(csvData.Name.loc[0:3])
csvData.reset_index(drop=True)
print(csvData.loc[0])
print(csvData.loc[0:4]) 
csvData.index = [0, 1,2,3,4,5]
print(csvData)
print(csvData.index)
print(csvData.loc["A"])

    Name  Age     City Course  Marks  Attendance
0   Ilma   22  Aligarh    MCA     88          92
1  Aliya   21    Delhi    BCA     91          89
2   Anas   19     Agra    BSc     76          81
3   Sara   23  Lucknow    MCA     85          95
4   Aman   20    Noida  BTech     79          84
5   Zoya   22  Aligarh    BCA     93          97

In [193]:
print(csvData[["Age","Name"]])

   Age   Name
0   22   Ilma
1   21  Aliya
2   19   Anas
3   23   Sara
4   20   Aman
5   22   Zoya

In [236]:
csvData.reset_index(drop=True)

    Name  Age     City Course  Marks  Attendance
0   Ilma   22  Aligarh    MCA     88          92
1  Aliya   21    Delhi    BCA     91          89
2   Anas   19     Agra    BSc     76          81
3   Sara   23  Lucknow    MCA     85          95
4   Aman   20    Noida  BTech     79          84
5   Zoya   22  Aligarh    BCA     93          97

In [253]:
print(csvData.iat[0,1])

22

In [238]:
jsonData=pd.read_json("store_data.json")
print(jsonData)

       name rating                   feedback   age
0     Alice     5             Great product!!  25.0
1       Bob   four       ok but late Delivery  30.0
2   Charlie    two            BAD EXPERIENCE    NaN
3     Diana      5                  Loved it!  28.0
4       Eve    3.5  Average - could be better  20.0
5     Alice      5       Great product again!  25.0

In [241]:
print(jsonData.loc[0:3,["name","rating","age"]])

       name rating   age
0     Alice     5   25.0
1       Bob   four  30.0
2   Charlie    two   NaN
3     Diana      5  28.0

In [245]:
print(jsonData.iloc[0:4,[0,1,3]])

       name rating   age
0     Alice     5   25.0
1       Bob   four  30.0
2   Charlie    two   NaN
3     Diana      5  28.0

In [250]:
print(jsonData["name"][0])
print(jsonData.at[0,"name"])

Alice
Alice

In [257]:
print(jsonData.iat[0,1])

5

In [297]:
a=25
print(jsonData.query("age > @a"))

    name rating              feedback   age
1    Bob   four  ok but late Delivery  30.0
3  Diana      5             Loved it!  28.0

In [307]:
info = jsonData[jsonData["age"] > 25][["name", "age"]]
print(info)   #important

    name   age
1    Bob  30.0
3  Diana  28.0

In [309]:
info.loc[1]
info.iloc[1]

name    Diana
age      28.0
Name: 3, dtype: object

In [318]:
print(jsonData.query("age >= 28 & rating == '5' "))

    name rating   feedback   age
3  Diana      5  Loved it!  28.0

In [319]:
print(jsonData.dtypes)
print(jsonData["rating"].unique())

name            str
rating          str
feedback        str
age         float64
dtype: object
<ArrowStringArray>
['5 ', 'four', 'two', '5', '3.5']
Length: 5, dtype: str

In [329]:
# jsonData.isnull()
# jsonData.isna()
# jsonData.isnull().sum()
update=jsonData.dropna()
print(update)
print(jsonData)

    name rating                   feedback   age
0  Alice     5             Great product!!  25.0
1    Bob   four       ok but late Delivery  30.0
3  Diana      5                  Loved it!  28.0
4    Eve    3.5  Average - could be better  20.0
5  Alice      5       Great product again!  25.0
       name rating                   feedback   age
0     Alice     5             Great product!!  25.0
1       Bob   four       ok but late Delivery  30.0
2   Charlie    two            BAD EXPERIENCE    NaN
3     Diana      5                  Loved it!  28.0
4       Eve    3.5  Average - could be better  20.0
5     Alice      5       Great product again!  25.0

In [331]:
update1=jsonData.dropna(axis=1)   #important
print(update1)

       name rating                   feedback
0     Alice     5             Great product!!
1       Bob   four       ok but late Delivery
2   Charlie    two            BAD EXPERIENCE
3     Diana      5                  Loved it!
4       Eve    3.5  Average - could be better
5     Alice      5       Great product again!

In [332]:
print(jsonData)

       name rating                   feedback   age
0     Alice     5             Great product!!  25.0
1       Bob   four       ok but late Delivery  30.0
2   Charlie    two            BAD EXPERIENCE    NaN
3     Diana      5                  Loved it!  28.0
4       Eve    3.5  Average - could be better  20.0
5     Alice      5       Great product again!  25.0

In [333]:
print(jsonData.fillna(0))

       name rating                   feedback   age
0     Alice     5             Great product!!  25.0
1       Bob   four       ok but late Delivery  30.0
2   Charlie    two            BAD EXPERIENCE    0.0
3     Diana      5                  Loved it!  28.0
4       Eve    3.5  Average - could be better  20.0
5     Alice      5       Great product again!  25.0

In [335]:
print(jsonData.ffill())

       name rating                   feedback   age
0     Alice     5             Great product!!  25.0
1       Bob   four       ok but late Delivery  30.0
2   Charlie    two            BAD EXPERIENCE   30.0
3     Diana      5                  Loved it!  28.0
4       Eve    3.5  Average - could be better  20.0
5     Alice      5       Great product again!  25.0

In [336]:
print(jsonData.bfill())

       name rating                   feedback   age
0     Alice     5             Great product!!  25.0
1       Bob   four       ok but late Delivery  30.0
2   Charlie    two            BAD EXPERIENCE   28.0
3     Diana      5                  Loved it!  28.0
4       Eve    3.5  Average - could be better  20.0
5     Alice      5       Great product again!  25.0

In [340]:
print(csvData)

    Name  Age     City Course  Marks  Attendance
a   Ilma   22  Aligarh    MCA     88          92
b  Aliya   21    Delhi    BCA     91          89
c   Anas   19     Agra    BSc     76          81
d   Sara   23  Lucknow    MCA     85          95
e   Aman   20    Noida  BTech     79          84
f   Zoya   22  Aligarh    BCA     93          97

In [346]:
csvData[["Marks","Attendance"]].duplicated()  #important

a    False
b    False
c    False
d    False
e    False
f    False
dtype: bool

In [357]:
csvData.loc[5, "Marks"] = 88
print(csvData)

    Name   Age     City Course  Marks  Attendance
a   Ilma  22.0  Aligarh    MCA   88.0        92.0
b  Aliya  21.0    Delhi    BCA   91.0        89.0
c   Anas  19.0     Agra    BSc   76.0        81.0
d   Sara  23.0  Lucknow    MCA   85.0        95.0
e   Aman  20.0    Noida  BTech   79.0        84.0
f   Zoya  22.0  Aligarh    BCA   93.0        97.0
5    NaN   NaN      NaN    NaN   88.0         NaN

In [358]:
csvData

    Name   Age     City Course  Marks  Attendance
a   Ilma  22.0  Aligarh    MCA   88.0        92.0
b  Aliya  21.0    Delhi    BCA   91.0        89.0
c   Anas  19.0     Agra    BSc   76.0        81.0
d   Sara  23.0  Lucknow    MCA   85.0        95.0
e   Aman  20.0    Noida  BTech   79.0        84.0
f   Zoya  22.0  Aligarh    BCA   93.0        97.0
5    NaN   NaN      NaN    NaN   88.0         NaN

In [359]:
result = csvData.drop_duplicates()
print(result)

    Name   Age     City Course  Marks  Attendance
a   Ilma  22.0  Aligarh    MCA   88.0        92.0
b  Aliya  21.0    Delhi    BCA   91.0        89.0
c   Anas  19.0     Agra    BSc   76.0        81.0
d   Sara  23.0  Lucknow    MCA   85.0        95.0
e   Aman  20.0    Noida  BTech   79.0        84.0
f   Zoya  22.0  Aligarh    BCA   93.0        97.0
5    NaN   NaN      NaN    NaN   88.0         NaN

In [360]:
csvData

    Name   Age     City Course  Marks  Attendance
a   Ilma  22.0  Aligarh    MCA   88.0        92.0
b  Aliya  21.0    Delhi    BCA   91.0        89.0
c   Anas  19.0     Agra    BSc   76.0        81.0
d   Sara  23.0  Lucknow    MCA   85.0        95.0
e   Aman  20.0    Noida  BTech   79.0        84.0
f   Zoya  22.0  Aligarh    BCA   93.0        97.0
5    NaN   NaN      NaN    NaN   88.0         NaN

In [366]:
csvData.drop_duplicates(inplace=True)

In [376]:
res=csvData.drop(csvData.index[6],inplace=True)  #important
print(res)

None

In [377]:
csvData

    Name   Age     City Course  Marks  Attendance
a   Ilma  22.0  Aligarh    MCA   88.0        92.0
b  Aliya  21.0    Delhi    BCA   91.0        89.0
c   Anas  19.0     Agra    BSc   76.0        81.0
d   Sara  23.0  Lucknow    MCA   85.0        95.0
e   Aman  20.0    Noida  BTech   79.0        84.0
f   Zoya  22.0  Aligarh    BCA   93.0        97.0

In [380]:
print(csvData.dtypes)  #types is plural Imporant

Name              str
Age           float64
City              str
Course            str
Marks         float64
Attendance    float64
dtype: object

In [381]:
jsonData

       name rating                   feedback   age
0     Alice     5             Great product!!  25.0
1       Bob   four       ok but late Delivery  30.0
2   Charlie    two            BAD EXPERIENCE    NaN
3     Diana      5                  Loved it!  28.0
4       Eve    3.5  Average - could be better  20.0
5     Alice      5       Great product again!  25.0

In [392]:
jsonData = jsonData.fillna(0)
jsonData["age"] = jsonData["age"].astype("int64")

In [397]:
jsonData
print(jsonData.dtypes)1

name          str
rating        str
feedback      str
age         int64
dtype: object